name: Build and Test

on:
  push:
    branches:
      - main
      - 44-github-action
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run npm run dev
        run: npm run dev || exit 0

      - name: Check for errors
        run: |
          if [ $? -eq 0 ]; then
            echo "No errors detected."
          else
            echo "Errors detected. Exiting..."
            exit 1
          fi
